### ISSUE TITLE
cassandra-operator and cassandra 

### ISSUE THREAD

**Issue by vishnugs** [Orange-OpenSource/cassandra-k8s-operator#116]
Hi Team,

Can this operator is production ready ? Also does it support backup & restore to and from aws ?
Is this compatible with  https://github.com/helm/charts/tree/master/incubator/cassandra

-Vishnu

**Comment by allamand** [comment]
Hi @vishnugs,

We plan to use the operator in production at the beginning of 2020.
We are currently working on backup & restore, we are studying many solutions such as https://github.com/instaclustr/cassandra-backup

For the compatibility, we are not compatible with the helm charts, as we have our own charts to deploy the operator, and then it's the operator that creates Cassandra clusters according to specified CassandraCluster custom ressource definition. But when #112 will be merged, the operator will be compatible with the official cassandra:3.11 image used by this helm.

I close the Issue since this is not a problem, but feel free to contionue the discussion.
